PastryFestival2021/PastryFestival2021/Areas/Admin/Controllers/NewsAdminController.cs
using AutoMapper;
using PastryFestival2021.ActionFilters;
using PastryFestival2021.Areas.Admin.ViewModels.News;
using PastryFestival2021.Models;
using PastryFestival2021.Models.Cmind;
using PastryFestival2021.Repositories;
using PastryFestival2021.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PastryFestival2021.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class NewsAdminController : BaseAdminController
    {
        private NewsRepository newsRepository = new NewsRepository();

        // GET: Admin/NewsAdmin
        public ActionResult Index(NewsIndexView model)
        {
            var query = newsRepository.Query(model.Title);
            var pageResult = query.ToPageResult<News>(model);
            model.PageResult = Mapper.Map<PageResult<NewsView>>(pageResult);
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            NewsView model;
            if (id == 0)
            {
                model = new NewsView();
                model.OnlineTime = DateTime.Now;
            }
            else
            {
                var query = newsRepository.GetById(id);
                model = Mapper.Map<NewsView>(query);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NewsView model)
        {
            bool hasFile = ImageHelper.CheckFileExists(model.ImageFile);
            if (ModelState.IsValid)
            {
                if (hasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, model.Image);
                    model.Image = ImageHelper.SaveImage(PhotoFolder, model.ImageFile);
                }

                News data = Mapper.Map<News>(model);
                data.UpdateTime = DateTime.Now;
                data.Updater = AdminInfoHelper.GetAdminInfo().ID;
                if (model.ID == 0)
                {
                    data.CreateTime = DateTime.Now;
                    data.Creater = AdminInfoHelper.GetAdminInfo().ID;
                    model.ID = newsRepository.Insert(data);
                }
                else
                {
                    newsRepository.Update(data);
                }

                ShowMessage(true, "儲存成功");
                return RedirectToAction(nameof(NewsAdminController.Edit), new { id = model.ID });
            }
            else
            {

                ShowMessage(false, "輸入資料有誤");
                return View(model);
            }
        }

        public ActionResult Delete(int id)
        {
            DeleteImage(id);
            newsRepository.Delete(id);
            ShowMessage(true, "刪除成功");
            return RedirectToAction(nameof(NewsAdminController.Index));
        }

        public ActionResult DeleteImage(int id)
        {
            var image = newsRepository.DeleteImage(id);
            //刪除圖片
            ImageHelper.DeletePhoto(PhotoFolder, image);
            ShowMessage(true, "刪除圖片成功");
            return RedirectToAction(nameof(NewsAdminController.Edit), new { id = id });
        }
    }
}

PastryFestival2021/PastryFestival2021/Areas/Admin/Views/NewsAdmin/Edit.cshtml
@model PastryFestival2021.Areas.Admin.ViewModels.News.NewsView
@{
    var title = Model.ID == 0 ? "新增最新消息" : "編輯最新消息";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    @title 管理
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card card-primary">
                <div class="card-header with-border">
                    <h3 class="card-title">@title</h3>
                </div>

                @using (Html.BeginForm("Edit", "NewsAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title)
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Image)
                            <br />
                            <p class="help-block">請上傳不超過3MB的圖片</p>
                            @Html.EditorFor(m => m.ImageFile, "_UploadImage", new { @PhotoFolder = "NewsPhoto" })
                            @if (!string.IsNullOrEmpty(Model.Image))
                            {
                                <img src="~/FileUploads/NewsPhoto/@Model.Image?v=@DateTime.Now.ToString("yyyyMMddHHmmss")" class="img-thumbnail" style="width:200px" />
                                @Html.HiddenFor(model => model.Image)
                                <br />
                                @Html.ActionLink("刪除圖片", "DeleteImage", new { id = Model.ID, type = "Image" }, new { @class = "btn btn-danger js-delete-confirm" })
                            }
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Content)
                            @Html.TextAreaFor(model => model.Content, new { @class = "form-control js-ckeditor" })
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.OnlineTime)
                            @Html.TextBoxFor(model => model.OnlineTime, new { @class = "form-control", @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.OnlineTime, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">儲存</button>
                        @if (Model.ID != 0)
                        {
                            @Html.ActionLink("刪除", "Delete", new { id = Model.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                        }
                        @Html.ActionLink("取消/回列表", "Index", "NewsAdmin", null, new { @class = "btn btn-default" })
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="~/Scripts/Admin/fileUpload.js"></script>
    <script src="~/Content/Admin/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>

    <!--DatePicker-->
    <link rel="stylesheet" href="//apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css">
    <script>
        $(window).on('load', function () {
            $("form").each(function () { $.data($(this)[0], 'validator', false); });
            $.validator.unobtrusive.parse("form");
        });
        $(function () {
            //Ckeditor init
            $('.js-ckeditor').each(function (i, e) {
                var id = $(e).attr('id');
                CKEDITOR.replace(id, {
                    filebrowserImageUploadUrl: "/Admin/NewsAdmin/Upload"
                });
            });
            var myDate = $.datepicker.parseDate("yy/mm/dd", $("#OnlineTime").val());
            var date = $.datepicker.formatDate("yy/mm/dd", myDate);
            $("#OnlineTime").val(date);
            $("#OnlineTime").datepicker({
                dateFormat: "yy/mm/dd"
            });
        });
        
        $('body').on('change', '.custom-file input[type="file"]', function () {
            const $this = $(this);
            var $customFile = $this.parent();

            var fileName = $this.val();
            var cleanFileName = fileName.replace('C:\\fakepath\\', " ");
            $customFile.find('.custom-file-label').html(cleanFileName);
        });
    </script>
}

PastryFestival2021/PastryFestival2021/Areas/Admin/Views/NewsAdmin/Index.cshtml
@model PastryFestival2021.Areas.Admin.ViewModels.News.NewsIndexView
@{
    var title = "最新消息";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    @title 管理
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "NewsAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @placeholder = "標題" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                                @Html.ActionLink("新增" + title, "Edit", "NewsAdmin", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">@title 列表</h3>
                </div>
                <div class="card-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row table-responsive no-padding">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover table-striped dataTable dtr-inline">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Title)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Image)
                                            </th>
                                            <th data-sorting="OnlineTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().OnlineTime)
                                            </th>
                                            <th data-sorting="UpdateTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().UpdateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Title)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Image)
                                            </th>
                                            <th data-sorting="OnlineTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().OnlineTime)
                                            </th>
                                            <th data-sorting="UpdateTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().UpdateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                        <tr>
                                            <td>
                                                @item.Title
                                            </td>
                                            <td>
                                                @if (!string.IsNullOrEmpty(item.Image))
                                                {
                                                    <img src="~/FileUploads/NewsPhoto/@item.Image" class="img-fluid" style="max-width:150px" />
                                                }
                                                else
                                                {
                                                    <p>無</p>
                                                }
                                            </td>
                                            <td>
                                                @item.OnlineTime.ToString("yyyy/MM/dd")
                                            </td>
                                            <td>
                                                @item.UpdateTime.ToString("yyyy/MM/dd HH:mm")
                                            </td>
                                            <td>
                                                @Html.ActionLink("編輯", "Edit", "NewsAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                                @Html.ActionLink("刪除", "Delete", "NewsAdmin", new { id = item.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}