PastryFestival2021/PastryFestival2021/ViewModels/Home/HomeView.cs
using PastryFestival2021.ViewModels.News;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PastryFestival2021.ViewModels.Home
{
    public class HomeView
    {
        public IEnumerable<NewsView> NewsList { get; set; }
        public int? Vote1Count { get; set; }
        public int? Vote2Count { get; set; }
        public int? Vote3Count { get; set; }
    }
}

PastryFestival2021/PastryFestival2021/Controllers/HomeController.cs
using AutoMapper;
using PastryFestival2021.ActionFilters;
using PastryFestival2021.Models;
using PastryFestival2021.Models.Cmind;
using PastryFestival2021.Repositories;
using PastryFestival2021.Utility.Cmind;
using PastryFestival2021.ViewModels.Home;
using PastryFestival2021.ViewModels.Member;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using PastryFestival2021.ViewModels.News;

namespace PastryFestival2021.Controllers
{
    public class HomeController : BaseController
    {
        private VoteLogRepository votelogRepository = new VoteLogRepository();
        private MemberRepository memberRepository = new MemberRepository();
        private NewsRepository newsRepository = new NewsRepository();


        public ActionResult Index(HomeView model)
        {
            var newsquery = newsRepository.List();
            if(newsquery.Count() > 0)
            {
                newsquery = newsRepository.List().Take(5);
            }
            model.NewsList = Mapper.Map<IEnumerable<NewsView>>(newsquery);
            model.Vote1Count = votelogRepository.Query(1)?.Count();
            model.Vote2Count = votelogRepository.Query(2)?.Count();
            model.Vote3Count = votelogRepository.Query(3)?.Count();

            return View(model);
        }

        public JsonResult Voted(int vid = 0)
        {
            MemberInfo memberInfo = MemberInfoHelper.GetMemberInfo();
            var result = "";
            if (memberInfo != null) {
                var member = memberRepository.SocialLogin(memberInfo.ID);
                if (member == null)
                {
                    result = "form";
                }
                else {
                    var query = votelogRepository.GetVoteLog(memberInfo.ID);
                    if (query == null)
                    {
                        votelogRepository.Insert(vid: vid, fid: memberInfo.ID, name: member.Name);
                    }
                    //測試
                    //result = "success";

                    result = query == null ? "success" : "voted";
                }
            }
            else
            {
                result = "error";
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [MemberAuthorize]
        public ActionResult Form()
        {
            var model = new MemberView();
            MemberInfo memberInfo = MemberInfoHelper.GetMemberInfo();
            var query = memberRepository.SocialLogin(memberInfo.ID);
            if (query != null)
            {
                model = Mapper.Map<MemberView>(query);
                model.ID = query.ID;
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Form(MemberView model)
        {
            var vid = Session["Vid"]?.ToString();
            MemberInfo memberInfo = MemberInfoHelper.GetMemberInfo();
            Session["Vid"] = null;
            if (memberInfo != null) {
                if (ModelState.IsValid)
                {
                    model.FBId = memberInfo.ID;
                    Member data = Mapper.Map<Member>(model);
                    if (model.ID == 0)
                    {
                        model.ID = memberRepository.Insert(data);                    
                    }
                    else
                    {
                        memberRepository.Update(data);
                    }
                    var query = votelogRepository.GetVoteLog(memberInfo.ID);
                    if (query == null)
                    {
                        int Vid = vid != null ? Convert.ToInt32(vid) : 0;
                        if (Vid != 0)
                        {
                            votelogRepository.Insert(vid: Vid, fid: memberInfo.ID, name: data.Name);
                            ShowMessage(true, "投票成功");
                        }
                    }
                    else
                    {
                        ShowMessage(false, "今日已投票，請明日再投");

                    }
                    return RedirectToAction("Index", "Home");
                }
            }
            
            return View(model);
        }

    }
}

PastryFestival2021/PastryFestival2021/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PastryFestival2021.Repositories;
using PastryFestival2021.ViewModels.News;

namespace PastryFestival2021.Controllers
{
    public class NewsController : BaseController
    {
        private NewsRepository newsRepository = new NewsRepository();
        // GET: News
        public ActionResult Index(NewsIndexView model)
        {
            var query = newsRepository.List();
            model.NewsList = Mapper.Map<IEnumerable<NewsView>>(query);
            return View(model);
        }
        public ActionResult Detail(int id)
        {
            var model = new NewsView();
            if (id != 0) {
                var query = newsRepository.GetById(id);
                if (query != null)
                {
                    model = Mapper.Map<NewsView>(query);
                }
                else {
                    RedirectToAction("Index", "Home");
                }
            }
            return View(model);
        }
    }
}

PastryFestival2021/PastryFestival2021/Views/Home/Form.cshtml
@model PastryFestival2021.ViewModels.Member.MemberView
@section head{
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <style>
        input {
            font-size: 22px
        }

        .row {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            margin-left:0;
            margin-right:0;
        }

        form input {
            width: 100%;
            height: 100%;
        }

            form input[type='submit'] {
                border: 0;
                font-size: 100%;
                text-align: center;
            }

        form .col-4 {
            text-align: right;
        }
    </style>
}
    <div class="area">
        <div class="form-group row container">
            <div class="conCon text-center">投票活動結束</div>
            @*<div class="conCon text-center">送出後成功投票並獲得抽獎機會</div>*@

        </div>
        @*@using (Html.BeginForm("Form", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(p => p.ID)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group row">
                <div class="col-md-1 col-xs-3">
                    @Html.LabelFor(p => p.Name)
                </div>
                <div class="col-md-4 col-xs-8">
                    @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = " text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-1 col-xs-3">
                    @Html.LabelFor(p => p.Phone)
                </div>
                <div class="col-md-4 col-xs-8">
                    @Html.TextBoxFor(p => p.Phone, new { @type = "tel", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-1 col-xs-3">
                    @Html.LabelFor(p => p.Email)
                </div>
                <div class="col-md-4 col-xs-8">
                    @Html.TextBoxFor(p => p.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-4 col-xs-7">
                    <input class="voteBtn text-center" width="200" type="submit" value="送出">
                </div>
            </div>
        }*@
    </div>
@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>

    <script>
        $(window).on('load', function () {
            $("form").each(function () { $.data($(this)[0], 'validator', false); });
            $.validator.unobtrusive.parse("form");
        });
    </script>
}

PastryFestival2021/PastryFestival2021/Views/Home/Index.cshtml
@model PastryFestival2021.ViewModels.Home.HomeView
@{
    ViewBag.Title = "Index";

}
@section head{
    <link href="~/Content/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Content/css/owl.theme.default.min.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Content/js/html5lightbox.js"></script>

    <script>
        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true
        })
    </script>

}
<div class="area">
    <div class="title visible"><img src="~/Content/images/newsTitle.png" alt=""></div>
    <div class="title visibleM"><img src="~/Content/images/newsTitleM.png" alt=""></div>
    <div class="newsList">
        @foreach (var item in Model.NewsList)
        {
            <a href="@Url.Action("Detail","News", new { id = item.ID })" class="newsBox">
                <div class="date">@item.OnlineTime.ToString("yyyy-MM-dd")</div>
                <div class="news">@item.Title</div>
            </a>
        }
    </div>
    <a href="@Url.Action("Index","News")" class="more">more</a>
</div>

@section scripts{
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/html5lightbox.js"></script>

    <script>
        $(function () {
            var extraOffset = 90;
            $('a[href=#event]').click(function () {
                $('html,body').animate({
                    scrollTop: $('#event').offset().top - extraOffset
                }, "show");
                return false;
            });
            $('a[href=#video]').click(function () {
                $('html,body').animate({
                    scrollTop: $('#video').offset().top - extraOffset
                }, "show");
                return false;
            });
            $('a[href=#link]').click(function () {
                $('html,body').animate({
                    scrollTop: $('#link').offset().top - extraOffset
                }, "show");
                return false;
            });
            //輪播
            setTimeout(function () {
                $('.videoCarousel').owlCarousel({
                    loop: false,
                    margin: 0,
                    nav: true,
                    dots: true,
                    autoplay: false,
                    //navClass: ["carouselNav_prevApp", "carouselNav_nextApp"],
                    navText: [" ", " "],
                    navContainerClass: "carouselNavApp",
                    items: 2,
                    responsive: {
                        0: {
                            items: 1
                        },
                        480: {
                            items: 1
                        },
                        769: {
                            items: 2
                        }
                    }

                });
            }, 1000);

        });
           @*$(".voteBtn").click(function () {
               var $this = $(this);
               const apiUrl = '@Url.Action("Voted")';
               $.get(apiUrl + '?vid=' + $this.data('vote'), function (result) {
                   if (result == "success") {
                       Swal.fire({
                           position: 'top-center',
                           icon: 'success',
                           title: '投票成功',
                           showConfirmButton: false,
                           timer: 2000
                       })
                       setTimeout(function () {
                           window.location.reload();
                       }, 2000);

                       window.location.hash = "mask";
                   }
                   else if (result == "error") {
                       window.location.href = "/SocialLogin/FBRegister" + "?vid=" + $this.data('vote');
                   } else if (result == "form") {
                       window.location.pathname = "/Home/Form"
                   } else {
                       Swal.fire({
                           position: 'top-center',
                           icon: 'error',
                           title: '今日已投票，請明日再投',
                           showConfirmButton: false,
                           timer: 2000
                       })
                   }
               });
        });*@
    </script>
}