PastryFestival2021/PastryFestival2021/Areas/Admin/Controllers/VoteAdminController.cs
using AutoMapper;
using PastryFestival2021.ActionFilters;
using PastryFestival2021.Areas.Admin.ViewModels.Vote;
using PastryFestival2021.Models;
using PastryFestival2021.Models.Cmind;
using PastryFestival2021.Repositories;
using PastryFestival2021.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PastryFestival2021.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class VoteAdminController : BaseAdminController
    {
        private VoteLogRepository votelogRepository = new VoteLogRepository();
        // GET: Admin/VoteAdmin
        public ActionResult Index(VoteIndexView model)
        {
            var query = votelogRepository.GetAll();
            var pageResult = query.ToPageResult<VoteLog>(model);
            model.PageResult = Mapper.Map<PageResult<VoteView>>(pageResult);
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            votelogRepository.Delete(id);
            ShowMessage(true, "刪除成功");
            return RedirectToAction(nameof(VoteAdminController.Index));
        }
    }
}

PastryFestival2021/PastryFestival2021/Areas/Admin/Views/VoteAdmin/Index.cshtml
@model PastryFestival2021.Areas.Admin.ViewModels.Vote.VoteIndexView
@{
    var title = "投票紀錄";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    @title 管理
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="row">
        <!--清單-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">@title 列表</h3>
                </div>
                <div class="card-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row table-responsive no-padding">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover table-striped dataTable dtr-inline">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().FBId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Name)
                                            </th>
                                            <th data-sorting="VoteId">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().VoteId)
                                            </th>
                                            <th data-sorting="CreateTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().CreateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().FBId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Name)
                                            </th>
                                            <th data-sorting="VoteId">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().VoteId)
                                            </th>
                                            <th data-sorting="CreateTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().CreateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                            var imgpath = "mask" + item.VoteId + ".png";
                                        <tr>
                                            <td>
                                                @item.FBId
                                            </td>
                                            <td>
                                                @item.Name
                                            </td>
                                            <td>
                                                    <img src="~/Content/images/@imgpath" class="img-fluid" style="max-width:100px" />
                                            </td>
                                            <td>
                                                @item.CreateTime.ToString("yyyy/MM/dd HH:mm")
                                            </td>
                                            <td>
                                                @Html.ActionLink("刪除", "Delete", "VoteAdmin", new { id = item.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}